import { describe, test, assertType } from "vitest";
import { AllKebabCaseAriaAttributes } from "./AllKebabCaseAriaAttributes";

describe("KebabCaseAriaAttributes", () => {
  test("attributes", () => {
    assertType<AllKebabCaseAriaAttributes>({
      "aria-activedescendant": "string",
      "aria-atomic": true,
      "aria-autocomplete": "none",
      "aria-busy": true,
      "aria-checked": "mixed",
      "aria-colcount": 1,
      "aria-colindex": 1,
      "aria-colspan": 1,
      "aria-controls": "string",
      "aria-current": "page",
      "aria-describedby": "string",
      "aria-details": "string",
      "aria-disabled": true,
      "aria-dropeffect": "copy",
      "aria-errormessage": "string",
      "aria-expanded": true,
      "aria-flowto": "string",
      "aria-grabbed": true,
      "aria-haspopup": "menu",
      "aria-hidden": true,
      "aria-invalid": true,
      "aria-keyshortcuts": "string",
      "aria-label": "string",
      "aria-labelledby": "string",
      "aria-level": 1,
      "aria-live": "off",
      "aria-modal": true,
      "aria-multiline": true,
      "aria-multiselectable": true,
      "aria-orientation": "horizontal",
      "aria-owns": "string",
      "aria-placeholder": "string",
      "aria-posinset": 1,
      "aria-pressed": true,
      "aria-readonly": true,
      "aria-relevant": "additions removals text",
      "aria-required": true,
      "aria-roledescription": "string",
      "aria-rowcount": 1,
      "aria-rowindex": 1,
      "aria-rowspan": 1,
      "aria-selected": true,
      "aria-setsize": 1,
      "aria-sort": "ascending",
      "aria-valuemax": 1,
      "aria-valuemin": 1,
      "aria-valuenow": 1,
      "aria-valuetext": "string",
    });
  });
});
